name: "flags"
shortDesc: "I echo all the flags that have been passed to my plugin as environment variables"
command: "bash -c env"
flags:
  - name: foo
    desc: foo
  - name: output
    shorthand: o
    desc: output format
